name: iglo_world
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.0
  fl_chart: ^0.6.1
  fancy_bottom_navigation: ^0.3.2
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  provider: ^3.1.0+1
  crypto: ^2.1.3
  modal_progress_hud: ^0.1.3
  geolocator: ^5.1.5
  animated_card: ^1.0.0+8
  shared_preferences: ^0.5.4+6
  get_it: ^3.0.3
  flutter_styled_toast: ^1.2.1
  search_widget: ^1.0.0
  date_format: ^1.0.8
  sweetalert: ^0.0.1
  pull_to_refresh: ^1.5.7
  permission_handler: ^4.1.0
  custom_navigator: ^0.3.0
  url_launcher: ^5.0.2
  path_provider: ^1.5.1
  image_picker: ^0.6.0+8
  video_player: ^0.10.1
  toast: ^0.1.5
  google_maps_flutter: ^0.5.21+15
  badges: ^1.1.0
  material_segmented_control: ^2.0.9
  timeline: 0.0.1
  carousel_pro: ^0.0.13
  flutter_money_formatter: ^0.8.3
  flutter_tags: ^0.4.5
  chips_choice: ^1.0.0
  share: ^0.6.3+5
  file_picker: ^1.5.0+2
  dio: ^3.0.8
  keyboard_visibility: ^0.5.6
  image_cropper: ^1.2.1
  awesome_card: ^1.1.0
  photo_view: ^0.9.2
  cached_network_image: ^2.0.0
  skeleton_text: ^1.0.0
  flutter_screenutil: ^1.0.2
  carousel_slider: ^1.4.1
  flutter_launcher_icons: "^0.7.3"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon_igloworld_flip.jpg"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
          weight: 400
